### ISSUE TITLE
[feat] HomeView 목록형 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#10]
### 작업에 대한 간단한 설명
- HomeView 내 목록형 옵션을 선택했을 때 보여줄 CollectionView UI 구현 작업

### TODO
- [x] CollectionViewCell UI 구현
- [x] HomeView 내 CollectionView와 연결
- [x] TestData를 통해 작동 확인

### 작업 일정(Optional)
2022.10.20 - 2022.10.20 (1일)
