### ISSUE TITLE
[fix] 다중 영상 분류 로직 개선

### ISSUE THREAD

**Issue by commitcomplete** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#105]
### 작업에 대한 간단한 설명
- 카드가 여러장이 한번에 터치가 되는 버그
    - 위에 있는 카드가 터치되어 움직인 동시에 뒤에 있는 카드가 동시 터치가 되어 한번에 5개까지 터치되는 버그
- 성공 or 실패 버튼 터치 버그
    - 카드 스와이핑이 끝나기 전 버튼이 터치될 경우 남은 카드가 존재함에도 분류 작업이 종료되는 버그

### TODO
- [x] 카드 다중 터치 제한
- [x] 버튼을 통한 성패 로직 수정
- [x] 버튼 클릭 애니매이션 구현
- [x] 카드 스와이핑 시 z축 기준 가장 상단에 위치시키는 작업

### 작업 일정
2022.11.08 - 2022.11.09

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.09|버튼을 통한 성패 로직 수정|
|2022.11.09|버튼 클릭 애니매이션 구현|
|2022.11.10|카드 다중 터치 제한|
|2022.11.10|카드 스와이핑 시 z축 기준 가장 상단에 위치시키는 작업|

### Optional
- `불편`
