### ISSUE TITLE
[feat] VideoCollectionView 구현 - WithOut Data

### ISSUE THREAD

**Issue by commitcomplete** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#11]
### 작업에 대한 간단한 설명
- 사용자가 발견하기에서 섹션을 터치했을때 이동하는 영상 나열 페이지의 UI를 구현한다.
- 데이터는 더미데이터 배열로 대체한다.

### TODO
- [ ] VideoCollectionView 의 UICollectionView 구현
- [ ] VideoCollectionView 의 동적 NavigationBar 구현
- [ ] VideoCollectionView 의 하단 toolbar 구현
- [ ] VideoCollectionView 의 다중선택 + 삭제
- [ ] VideoCollectionView 의 영상 디테일뷰 네비게이션

### 작업 일정(Optional)
2022.10.20 - 2022.10.21
