### ISSUE TITLE
[style] 더미 코드 정리

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#111]
### 작업에 대한 간단한 설명
- 테스트용으로 작성해 뒀던 폴더, 파일, 주석 등 정리 작업

### TODO
- [ ] 꼬마 파트 작업
- [ ] 도도 파트 작업
- [ ] 레드 파트 작업
- [ ] 류하 파트 작업
- [ ] 엘리제 파트 작업
- [ ] 예니 파트 작업
- [ ] 이안 파트 작업

### 작업 일정
2022.11.04 - 2022.11.13

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|
|2022.00.00|SequenceNumber|
|2022.00.00|SequenceNumber|
|2022.00.00|SequenceNumber|
|2022.00.00|SequenceNumber|
|2022.00.00|SequenceNumber|

### 참고 사항
- 테스트용으로 작성해 뒀던 폴더, 파일, 주석 등 정리 작업이 끝나면 체크 박스 체킹 부탁드려요

### 이슈 제안자
- @hminkim
