### ISSUE TITLE
[feat] Swipe 카드 내부에 영상을 embed 합니다.

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#12]
### 작업에 대한 간단한 설명
- `AVFoundation` 과 `AVKit` 을 이용하여 Swipe 카드 내부에 영상을 embed 합니다. 

### TODO
- [x] 목업 데이터 모델을 생성합니다.
- [x] 여러가지의 목업 데이터를 생성합니다.
- [x] Swipe 카드 내부에 영상을 embed 하는 작업을 합니다.

### 작업 일정(Optional)
2022.10.22 - 2022.10.22 (작업일자)
