### ISSUE TITLE
[feat] 클라이밍장 명 입력 자동완성 기능 추가

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#151]
### 작업에 대한 간단한 설명
- 클라이밍장명을 입력할 때 자동완성을 통해 방문한 적이 있는 클라이밍장을 편하게 입력할 수 있게 도와주기.

### TODO
- [x] 방문할 클라이밍장명을 저장하고 불러올 데이터구조 생성 혹은 로직 추가
- [x] 클라이밍장 자동완성 UI 추가
- [x] 클라이밍장 자동완성 로직 추가

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
