### ISSUE TITLE
[feat] ViewDetailView 내 클라이밍장명, 방문 날짜 변경 수정 로직 분리 및 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#158]
### 작업에 대한 간단한 설명
- 컬렉션뷰로 나가고 싶었으나, 뒤로 가기 버튼이 나오지 않고 슬라이드를 통해서도 영상 정보창이 내려가지 않고, 뒤에 있는 영상을 눌렀을 때에도 반응이 없어서 아예 영상 정보 창을 닫는 방법을 찾지 못함.

### TODO
- [ ] 클라이밍장명 변경, 방문 날짜 변경 로직의 분리
- [ ] 클라이밍장명 변경, 방문 날짜 변경 버튼 분리한 UI 구현
- [ ] 클라이밍장명 변경, 방문 날짜 변경 버튼 분리한 UI에 로직 연결

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
