### ISSUE TITLE
[fix] LevelAndPFSettingView 내 레벨 설정 버튼 반응성 개선

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#161]
### 작업에 대한 간단한 설명
- 분류 뷰에서 레벨 설정 버튼이 제대로 잘 눌리지 않음

### TODO
- [ ] 레벨 설정 버튼 UI 변경
    - [ ] `StackView`에 라운드 주기
    - [ ] `StackView`에 그림자 주기
    - [ ] 레벨이 선택 되었을 때 그림자 `.orrBlue`로 변경

### 작업 일정
2022.11.15 - 2022.11.16

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.15|레벨 설정 버튼 UI 변경|

### Optional
- Sketch의 Rinda 디자인 참고
