### ISSUE TITLE
[Fix] 영상 디테일 뷰 수정

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#173]
### 작업에 대한 간단한 설명
- 유저 테스트 기반으로 뽑아낸 액션아이템들을 작업하려고 합니다.
- `VideoDetail`의 태스크들을 먼저 진행할 예정이에요.

|<img src="https://user-images.githubusercontent.com/77262576/201853930-6888cd23-0bfc-4b24-8ae1-1e3ffce37998.gif" width="200" height="420"/>|<img src="https://user-images.githubusercontent.com/77262576/201853564-4b7944ef-0f2a-4e6f-bb58-719d4407d5ab.gif" width="200" height="420"/>|<img src="https://user-images.githubusercontent.com/77262576/201855274-81cc633f-3505-4d70-9215-54054b6e93c0.PNG" width="200" height="420"/>
|:---:|:---:|:---:|
|클라이밍장 이름 및 날짜 변경 뷰|레벨 수정 뷰의 Picker|영상 삭제 버튼|

### TODO
- [x] 레벨 수정 뷰에서 피커만 설정해도 바로 레벨값이 변경되도록 수정
- [x] 영상 삭제하기 경고창의 텍스트 색상을 빨간색으로 변경
- [ ] 클라이밍장 이름 변경 뷰와 날짜 변경 뷰의 분리

**Comment by yeniful** [comment]
중복 작업으로 이슈 닫습니다!
