### ISSUE TITLE
[feat] MyActivityView 데이터 연결 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#202]
### 작업에 대한 간단한 설명
- MyActivityView 내에 차트와 통계를 보여주기 위한 데이터를 불러오는 기능을 구현합니다.

### TODO
- [x] 나에 대한 기록 통계 뷰 데이터 호출 구현
- [x] 차트1 데이터 호출 구현
- [x] 차트2 데이터 호출 구현

### 작업 일정(Optional)
2022.11.19 - 2022.11.20 (2일)

### Optional
- Lo-Fi 기반 데이터 호출 구현 
- Hi-Fi 디자인 이후 디자인 맞춰 데이터 호출 구현 수정 예정
