### ISSUE TITLE
[feat] MyActivityView Hi-Fi UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#210]
### 작업에 대한 간단한 설명
- MyActivityView에 Hi-Fi 디자인을 적용합니다.

### TODO
- [x] 내 활동 구현
  - [x] 카드 Asset 추가하기
  - [x] 레이아웃 잡기
  - [x] 카드 위에 레이블 띄우기
- [x] 도전 구현
  - [x] 모든 도전 차트 UI 구현
  - [x] 모든 도전 차트 데이터 구현
  - [x] 성장 차트 UI 구현
  - [x] 성장 차트 데이터 구현
- [x] 정보 구현
  - [x] 홈짐 차트 UI 구현
  - [x] 홈짐 차트 데이터 구현
  - [x] 경력 데이터 구현
  - [x] 경력 편집 구현 → Picker 재활용

- [ ] 데이터가 없을 때 보여줄 PlaceHolder 추가

### 작업 일정(Optional)
2022.11.20 - 2022.11.21 (2일)

### Optional
- Hi-Fi 디자인이 나오면 작업 착수 예정
