### ISSUE TITLE
[feat] VideoDetailView 내 날짜, 클라이밍장 수정 분리

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#214]
### 작업에 대한 간단한 설명
- VideoDetailView에서 해당 영상의 날짜와 클라이밍장 정보에 대한 수정 로직을 분리해야 합니다.
- 로직 분리에 따라, 두 정보에 대한 진입점이 분리되기 위한 UI 수정이 필요합니다.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/39216546/202903651-9751d708-5dd6-44e2-8d94-a772948f7a32.png">

### TODO
- [x] VideoInfoView 내 UI 개편
- [x] 영상 날짜 수정 로직과 클라이밍장 정보 수정 페이지 분리
- [x] DataManager에 수정 로직 분리 및 적용

### 작업 일정(Optional)
2022.11.21 02:30 - 2022.11.21. 04:25 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
