### ISSUE TITLE
[design] 영상 업로드 중 날짜 선택, 클라이밍장명 입력 뷰 UI 개선

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#215]
### 작업에 대한 간단한 설명
- Upload 과정에서 3차 스프린트 디자인 적용에 따른 UI 변경사항을 적용해야 합니다.
- 해당 변경사항은 영상 정보 수정 페이지에서도 동일하게 적용되어야 합니다.

### TODO
- [x] DateSettingView 내 UI 수정
  - [x] 타이틀 수정
- [x] GymSettingView 내 UI 수정
  - [x] 타이틀 수정
  - [x] UITextField 수정
- [x] UI 수정사항을 영상 정보 수정 페이지에도 동일하게 적용

**추가**
- [x] 클라이밍장명 입력 20자 제한 기능의 구현 

### 작업 일정(Optional)
2022.11.21 01:42 - 2022.11.21 02:30 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
