### ISSUE TITLE
[feat] 루트파인딩 메인페이지의 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#221]
### 작업에 대한 간단한 설명
- 루트파인딩 페이지의 메인 UI를 구현합니다.

### TODO
- [x] 네비게이션 바 타이틀과 버튼 추가
- [x] 예쁜 Segment Control 구현
- [x] 카드 뷰 UI 구현
- [x] CollectionView 구현
- [x] 편집 모드 UI 구현
- [x] 삭제 알림 토스트 메시지 구현
- [ ] 데이터 로딩 중 보여줄 Skeleton screen 구현
- [x] 영상이 없을 때 보여줄 PlaceHolder View 구현

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
