### ISSUE TITLE
[feat] 루트파인딩 메인페이지의 데이터 연결

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#222]
### 작업에 대한 간단한 설명
- 루트파인딩 메인페이지의 UI에 데이터를 연결해 뷰를 구성합니다.

### TODO
- [x] DataManager로부터 데이터 받아와 적합한 형태로 가공
- [x] CollectionView에 데이터 연결
- [x] 편집모드 데이터 수정 및 삭제 구현

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
