### ISSUE TITLE
[feat] 루트파인딩 메인페이지의 데이터 구조 설계 및 DataManager 함수 작성

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#223]
### 작업에 대한 간단한 설명
- 루트파인딩 메인페이지 UI를 구성하기 위한 데이터 구조 설계와 입출력 함수의 작성이 필요합니다.

### TODO
- [x] 루트파인딩 기능의 데이터 구조 및 UI를 위한 데이터 전달 방식 설계
- [x] CoreData 내 설계한 데이터 구조 작성
- [x] UI 구성을 위한 루트파인딩 데이터 전달 처리 DataManager 내 함수 구현
- [x] 루트파인딩 데이터 수정 및 삭제 처리 DataMangaer 내 함수 구현

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
