### ISSUE TITLE
[feat] 루트파인딩 이미지 추가 UI, 로직 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#224]
### 작업에 대한 간단한 설명
- 루트파인딩 할 문제를 추가하기 위해 2가지 기능 --카메라로 촬영 기능 or 사진 앱에서 이미지 불러오기 기능--을 구현합니다.

### TODO
**UI**
- [x] 카메라 뷰 UI 구현
- [x] 이미지 피커 (UIImagePicker) 호출 UI 작성 -> PHPicker로 대체 구현

**Logic**
- [x] 카메라 기능 구현 (16:9 비율로 이미지 촬영만 가능한 카메라 기능)
- [x] 카메라 촬영 / 이미지 선택 후 다음 페이지로 넘겨줄 이미지 데이터 준비
