### ISSUE TITLE
[feat] 루트파인딩 기록하기 뷰 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#225]
### 작업에 대한 간단한 설명
- 문제 이미지를 받아와 루트파인딩 기록 UI를 구현합니다.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/202909237-f3846f0b-2544-4049-8516-e3c0ddb97a87.png">

### TODO
- [x] 뷰의 색상테마를 다크테마로 고정
- [x] 화면 내 버튼 작성
- [x] 하단 페이지 UI 구현
- [x] 현재 페이지 번호 알려주는 UI 구현
- [x] 손 발 아이콘, 삭제 버튼 추가
- [x] 삭제 모드 UI 작성

- ~힘 방향 표시 UI 작성~

### 작업 일정(Optional)
2022.11.25 - 2022.11.26 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.25.|하단 페이지 UI 구현|
|2022.11.26.|화면 내 버튼 작성|
|2022.11.26.|현재 페이지 번호 알려주는 UI 구현|
|2022.11.26.|삭제 모드 UI 작성|
|2022.11.26.|손 발 아이콘, 삭제 아이콘 추가|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
