### ISSUE TITLE
[feat] 루트파인딩 기록하기 뷰 로직 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#226]
### 작업에 대한 간단한 설명
- 루트파인딩 기록하기 기능에 대한 로직을 구현합니다.

### TODO
- [x] 하단 루트파인딩 페이지 추가 로직 구현
- [ ] 제스처를 통해 손, 발 아이콘 찍기 기능 구현
- [ ] 아이콘에 힘 방향 입력 기능 구현
- [ ] 위 2개 항목이 페이지마다 별도로 관리되도록 기능 구현
- [ ] 추가한 아이콘을 이동하는 기능 구현
- [ ] 이동 시 휴지통 UI 보여주기 + 삭제 기능 구현
- [ ] 손, 발 개수 제한에 따른 토스트 메시지 구현
- [x] 페이지 삭제 기능 구현
- [x] 작성한 기록을 저장하기 페이지로 전달

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
