### ISSUE TITLE
[feat] 루트파인딩 저장하기 UI 및 로직 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#227]
### 작업에 대한 간단한 설명
- 루트파인딩 마지막 시퀀스인 저장하기 UI 및 로직을 구현합니다.

### TODO
**UI**
- [x] 다크테마 적용
- [x] UIPageView 구현
- [x] 하단 썸네일 리스트 구현
  - [x] 현재 페이지 번호 보여주는 UI 구현
- [x] 저장하기 버튼 UI 구현

**Logic**
- [x] 각 뷰를 이미지로 저장하는 기능 구현
- [x] 썸네일 리스트 스크롤 기능 구현
- [x] 페이지 선택시 위 PageView에서 해당 이미지를 크게 보여주는 기능 구현
- [x] DataManager에 작성한 루트파인딩 기록을 저장하는 기능 구현

### 작업 일정(Optional)
2022.11.25 - 2022.11.30

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.26|페이지 선택시 위 PageView에서 해당 이미지를 크게 보여주는 기능 구현|
|2022.11.27|썸네일 리스트 스크롤 기능 구현|
|2022.11.27|루트파인딩 저장하기 UI 구현|
|2022.11.28|각 뷰를 이미지로 저장하는 기능 구현|
|2022.11.29|모든 뷰에 기본 다크테마 적용|
|2022.11.30|DataManager에 작성한 루트파인딩 기록을 저장하는 기능 구현|

### Optional
- 데이터 플로우에 대한 이해 필요
