### ISSUE TITLE
[feat] 공유를 위한 영상에 이미지 추가하여 export 하는 기능 추가

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#230]
### 작업에 대한 간단한 설명
- 클라이밍 영상에 이미지 레이어를 추가한 뒤 export 하는 기능 추가

### TODO
- [x] export될 영상 확인을 위한 모달 뷰 추가
- [x] 영상에 이미지 레이어를 얹혀서 export 하는 기능 추가
- [x] 난이도 컬러를 선택할 수 있는 기능 추가

### 작업 일정(Optional)
2022.11.19 - 2022.11.23

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.19|export될 영상 확인을 위한 모달 뷰 추가|
|2022.11.22|영상에 이미지 레이어를 얹혀서 export 하는 기능 추가|
|2022.11.23|난이도 컬러를 선택할 수 있는 기능 추가|

### 비고
- UI 디자인과 기능 구현을 동시에 진행 후 디자인 가이드에 맞춘 UI 제작
- 다양한 영상을 한번에 선택할 수 있는 기능 추가를 위해 빠른 작업 요망
