### ISSUE TITLE
[feat] MyActivityView 이미지 생성 + 공유 기능 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#232]
### 작업에 대한 간단한 설명
- MyActivityView에서 자신을 표현할 수 있는 볼더링 카드를 생성하고 공유하는 기능을 구현합니다.
- 해당 카드에는 자신이 볼더링을 시작한 지 며칠 째인지, 홈짐이 어디인지에 대한 정보를 담고 있습니다.

### TODO
- [x] Export 기능 구현
  - [x] 공유하기 버튼 추가
  - [x] 공유하기 액션시트 띄우기
  - [x] 카드 이미지 가공해 내보내기

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
