### ISSUE TITLE
[design] MyActivityView 린다 디자인 피드백 반영

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#247]
### 작업에 대한 간단한 설명
- MyActivityView 린다의 디자인 피드백을 반영합니다.

### TODO
- [x] Card 내 Padding이 통일되도록 수정
- [x] Chart 내 세로선 추가
- [x] Chart 내 점선 추가

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
