### ISSUE TITLE
[design] HomeView 린다 디자인 피드백 반영

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#249]
### 작업에 대한 간단한 설명
- HomeView 린다 디자인 피드백 반영

### TODO
- [x] 버튼 크기 조정
- [x] 앨범형 카드 상하 여백 조정
- [x] 앨범형 카드 레이블 간의 여백 조정
- [x] 목록형 셀 디바이더 길이 조절
- [x] 목록형 셀 Header 디바이더 제거

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
