### ISSUE TITLE
[feat] 영상 업로드 이전 과정 뷰 제작 및 코드 이주

### ISSUE THREAD

**Issue by RuyHa** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#26]
### 작업에 대한 간단한 설명
- 소통의 부재로 인해 제 코드가 이민을 가게 되었습니다.
- 업로드 이전에 있는 뷰도 제가 제작 하겠습니다.

### TODO
- [ ] 달력이 들어간 뷰 추가
- [ ] 클라이밍장 이름이 들어간 뷰 추가
- [ ] 업로드 코드 3차 이주
