### ISSUE TITLE
[fix] RouteFindingCameraViewController 오류 수정

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#289]
### 작업에 대한 간단한 설명
재검토 작업을 통해 발견했던 RouteFindingCameraViewController의 오류를 수정합니다.
1. UIImage Type으로 들고올 수 없는 사진에 대해 처리하기
2. iCloud 및 네트워크 환경을 사용해야하는 사진에 대한 처리하기
 2 - a. 네트워크 환경을 사용해야하는 경우, Loading Indicator 넣기
3. 카메라를 사용하는 경우, 정상적으로 사진을 찍었음에도 사진이 불러와지지 않는 에러 해결하기
4. 카메라 버튼 터치 시, 다른 버튼과의 Interaction 제한

### TODO
- [x] UIImage Type으로 들고올 수 없는 사진 처리
- [x] iCloud 및 네트워크 환경을 사용해야하는 사진 처리
- [x] 네트워크 환경을 사용해야하는 경우, Loading Indicator 처리
- [x] 카메라를 사용하는 경우, 정상적으로 사진을 찍었음에도 사진이 불러와지지 않는 에러 해결
- [x] 카메라 버튼 터치 시, 다른 버튼과의 Interaction 제한

### 작업 일정
2022.11.29 - 2022.11.29
