### ISSUE TITLE
[feat] HomeView UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#3]
### 작업에 대한 간단한 설명
- HomeView(발견하기 뷰) UI 구현

### TODO
- [x] 로고를 위한 Sticky Header 뷰 UI 구현
- [x] 카드 뷰가 담길 Collection 뷰 UI 구현
- [x] CollectionView의 내부 카드 UI 구현
- [x] Toolbar 뷰 UI 구현

### 작업 일정(Optional)
2022.10.19 - 2022.10.19 (1일)
