### ISSUE TITLE
[feat] gesture 관련 추가 작업

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#332]
### 작업에 대한 간단한 설명
- 크리티컬한 기능들을 우선으로 수정을 하겠습니다. 
- 다음과 같은 항목들은 다음 스프린트로 넘길 예정입니다.
    - hand point, foot point 저장하기 갯수 제한 + alert
    - 루트파인딩 방향

### TODO
- [x] pangesture의 .ended포인트 찾기 
  - [x] .ended에서 trashView 숨기기
  - [x] .ended시 buttonView와 point데이터가 삭제
  - [x] buttonView와 trashView가 맞닿을 때 trashView 이미지 "delete-destructive"로 전환
