### ISSUE TITLE
[feat] 루트파인딩 화면 내 이미지 화질 개선

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#338]
### 작업에 대한 간단한 설명
- 루트파인딩 디테일, 루트파인딩 피처 화면 내 이미지의 화질 개선이 필요합니다.

`generateCardViewThumbnail()` 함수 내 시그니쳐 변경으로 수정 가능할 것 같습니다.
해당 함수에 인자로 targetSize를 (500, 500)을 고정으로 넣고, 값을 지정했을 때 해당 타겟 값에 대한 크기의 이미지를 호출하는 방식을 활용하면 될 것 같아요.

### TODO
- [x] 메소드 매개변수 설정
- [x] RouteFindingSectionViewController thumbnail 화질 개선
- [x] RouteFindingDetailViewController thumbnail 화질 개선

### 이슈 제안자
- @sm-amoled
