### ISSUE TITLE
[fix] 루트파인딩 저장하기 뷰 내 수정사항

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#350]
### 작업에 대한 간단한 설명
- 이미지가 크롭되어 저장되고 있음
- 이미지가 하나만 저장되고 있음

### TODO
- [x] 이미지가 크롭되지 않고 저장되도록 변경
- [x] 이미지가 모두 저장되게 하거나 or 이미지 하나/모두 저장 선택지를 제공하기
- [x] 저장된 이미지의 개수에 따른 토스트 메세지 텍스트 변경

### 작업 일정(Optional)
2022.12.01 - 2022.12.01

|작업일자|작업 내용|
|:---:|:---:|
|2022.12.01|이미지가 크롭되지 않고 저장되도록 변경|
|2022.12.01|이미지가 모두 저장되게 하거나 or 이미지 하나/모두 저장 선택지를 제공하기|
|2022.12.01|저장된 이미지의 개수에 따른 토스트 메세지 텍스트 변경|

### 이슈 제안자(Optional)
- @sm-amoled
