### ISSUE TITLE
[chore] 배포 전 마지막 프로젝트 파일 정리

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#375]
### 작업에 대한 간단한 설명
- 배포 전 마지막으로 프로젝트 파일 정리

### TODO
- [x] Display Name 수정
- [x] 앱 배포 버전 수정
- [x] 앱 기본 언어 수정

### 이슈 제안자(Optional)
- @hminkim
