### ISSUE TITLE
[feat] 영상 상세 뷰 작성

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#38]
### 작업에 대한 간단한 설명
- 분류된 영상을 재생하고 상세 정보를 볼 수 있는 뷰 제작

### TODO
- [x] 기본 뷰 뼈대 작업
- [x] 영상 상세 뷰에서 상세 정보 입력
    - [x] 피드백 입력 및 수정 뷰 생성
    - [x] 난이도 입력 및 수정 뷰 생성
    - [x] 날짜 정보 입력 및 수정 뷰 생성
- [x] 영상 재생 뷰에서 영상 재생 기능 구현

### 작업 일정(Optional)
2022.10.21 - 2022.10.24

|작업일자|작업 내용|
|:---:|:---:|
|2022.10.23|기본 뷰 뼈대 작업|
|2022.10.24|영상 상세 뷰에서 상세 정보 입력|
|2022.10.24|영상 재생 뷰에서 영상 재생 기능 구현|

### Optional
- 기능을 구현할 때 데이터 플로우를 고려하면서 코드 작성
