### ISSUE TITLE
[fix] 오류수정

### ISSUE THREAD

**Issue by RuyHa** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#396]
### 작업에 대한 간단한 설명

- 루트 파인딩 삭제 버튼 오토레이아웃 수정
- 루트 파인딩 편집하기 모드 X버튼 워딩 수정 (삭제 → 나가기)
- 류하 기기에서 크래시나는 원인 파악
- 카메라 예외처리 강제 언래핑 수정
- 카드 제스쳐로 분류시 빠르게 연타 하면 앱 꺼짐이슈

### TODO
- [x] 루트 파인딩 삭제 버튼 오토레이아웃 수정
- [x] 루트 파인딩 편집하기 모드 X버튼 워딩 수정 (삭제 → 나가기)
- [x] 류하 기기에서 크래시나는 원인 파악 => 원인 파악 불가 재설치 하니 발생 안함
- [x] 카메라 예외처리 강제 언래핑 수정
- [x] 카드 제스쳐로 분류시 빠르게 연타 하면 앱 꺼짐이슈

### 작업 일정(Optional)
2022.00.00 - 2022.00.00 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.00.00|SequenceNumber|

### Optional
- 작업 전 숙지 사항

### 이슈 제안자(Optional)
- @인물 멘션
- 이슈 담당자 ≠ 작업 담당자의 케이스에 명시해주세요.
