### ISSUE TITLE
[feat] CoreDataManager 구현: UPLOAD & DELETE

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#40]
### 작업에 대한 간단한 설명
- Core Data Model의 CRUD(생성, 읽기, 수정, 삭제) 작업 중 U와 D 파트를 구현
- 업로드된 영상에 대한 수정 및 삭제 처리에 대한 플로우 작성과 함께 로직을 구현할 예정입니다.

### TODO
- [x] Update, Delete 작업에 대한 데이터 플로우 구상
- [x] Update 로직 구현
- [x] Delete 로직 구현

### 작업 일정
2022.10.23 - 2022.10.25

### Optional
- 해당 이슈 작업 후 1st Sprint에 대한 기본적인 CoreData 관련 기능이 구현 완료될 것으로 예상됩니다.
