### ISSUE TITLE
[feat] HomeView CoreData에서 데이터 받아와 보여주기 작업

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#44]
### 작업에 대한 간단한 설명
- HomeView UI에 CoreDataMaganer를 통해 받아온 데이터를 보여주는 작업 

### TODO
- [x] CoreDataManager 함수 및 코드 활용 방법 이해
- [x] 앨범형 데이터 보여주기 구현
  - [x] 오름/내림차순 정렬 기능 구현
  - [x] 필터링 기능 구현
- [x] 목록형 데이터 보여주기 구현
  - [x] 오름/내림차순 정렬 기능 구현
  - [x] 필터링 기능 구현
- [x] ~Cell 선택 시 다음 NavigationView 호출 함수 구현~

### 작업 일정
2022.10.24 - 2022.10.25 (2일)

|작업일자|작업 내용|
|:---:|:---|
|2022.10.24.|CoreDataManager 함수 및 코드 활용 방법 이해|
|2022.10.24.|앨범형 데이터 보여주기 구현|
|2022.10.25.|오름/내림차순 정렬 기능|
|2022.10.25.|필터링 기능 구현|
|2022.10.24.|목록형 데이터 보여주기 구현|
|2022.10.25.|오름/내림차순 정렬 기능 구현|
|2022.10.25.|필터링 기능 구현|
|도도|~Cell 선택 시 다음 NavigationView 호출 함수 구현~|
