### ISSUE TITLE
[feat] 카드 없애는 제스처와 버튼, 그리고 성공 실패 분류 로직을 추가합니다.

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#50]
### 작업에 대한 간단한 설명
- 기존에는 카드의 스와이프 제스처만 구현했는데 실제로 성공과 실패를 분류해주는 로직을 추가하려고 합니다.
- 또한 카드 밑에 버튼을 추가해서 스와이프와 같은 동작을 하는 버튼 기능을 추가하고자 합니다.
<img width="802" alt="스크린샷 2022-10-25 오전 1 32 24" src="https://user-images.githubusercontent.com/77262576/197578090-45fe6470-c88e-444e-b7d4-aa95dff4c778.png">

### TODO
- [x] 카드를 Swipe 했을 때, 카드가 시야에서 사라지는 기능을 구현합니다.
- [ ] 카드를 Swipe 했을 때, 카드의 데이터가 지워지는 기능을 구현합니다.
- [x] 성공 실패 버튼 UI 구현
- [x] 성공 실패 버튼 로직 구현

### 작업 일정
2022.10.24 - 2022.10.25
