### ISSUE TITLE
[feat] SwipeableCardView 의 전체적인 UI 와 로직을 구현합니다. 

### ISSUE THREAD

**Issue by LeeSungNo-ian** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#51]
### 작업에 대한 간단한 설명
- 암벽의 난이도를 입력할 수 있는 `.wheel` UI 와 로직을 구현합니다.
- 암벽 영상 분류가 끝났을 때 보여지는 UI (빈 카드 + 메세지) 를 구현합니다.
- SwipeableCardView 의 전체적인 UI 를 구현합니다.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/78950704/197578862-1f34a719-f1b1-4030-b68f-9878c0149057.png">

### TODO
- [ ] 암벽의 난이도를 입력할 수 있는 `.wheel` UI 와 로직을 구현합니다.
- [ ] 암벽 영상 분류가 끝났을 때 보여지는 UI (빈 카드 + 메세지) 를 구현합니다.
- [ ] SwipeableCardView 의 전반적인 UI 를 구현합니다.

### 작업 일정(Optional)
2022.10.25 - 2022.10.25
