### ISSUE TITLE
[feat] VideoDetailView의 디테일 작업

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#55]
### VideoDetailView의 디테일 작업
- #38 UI만 작업된 코드에 이벤트나 FIXME 키워드 디테일 작업

### TODO
- [x] 네비게이션바에서 영상 재생 및 일시정지 토글 버튼 구현
- [x] 네비게이션바에서 영상 음소거 토글 버튼 구현
- [x] 피드백 입력하기 버튼 로직 구현
- [x] @commitcomplete 가 작업한 뷰와 네비게이션 링크 연결

### 작업 일정(Optional)
2022.10.25 - 2022.10.26

|작업일자|작업 내용|
|:---:|:---:|
|2022.10.25|네비게이션바에서 영상 재생 및 일시정지 토글 버튼 구현|
|2022.10.25|네비게이션바에서 영상 음소거 토글 버튼 구현|
|2022.10.25|피드백 입력하기 버튼 로직 구현|

### Optional
- 데이터 플로우를 고려한 함수 및 로직 작성

**Comment by commitcomplete** [comment]
모달 연결해 놓았습니다!
