### ISSUE TITLE
[fix] 프로젝트 셋팅

### ISSUE THREAD

**Issue by RuyHa** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#58]
### 작업에 대한 간단한 설명
- 1. 화면 세로모드 고정 코드 추가
- 2. 아이패드 지원 제한 추가
- 3. 포토라이브러리 안내문 및 설명 코드 추가

### TODO
- [ ] 화면 세로모드 고정 코드 추가
- [ ] 아이패드 지원 제한 추가
- [ ] 포토라이브러리 안내문 및 설명 코드 추가
