### ISSUE TITLE
[feat] HomeView → 다른 View 데이터 전달 코드 구현

### ISSUE THREAD

**Issue by sm-amoled** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#66]
### 작업에 대한 간단한 설명
- 도도가 작업중인 "VideoCollectionView"로 Navigation 이동과 함께 데이터 전송 구현 필요
- 꼬마가 작업중인 "VideoDetailView"로 Navigation 이동과 함께 데이터 전송 구현 필요

### TODO
- [x] SectionData 데이터구조 수정
- [x] HV → VideoCollectionView 데이터 전달 구현
- [x] HV → VideoDetailView 데이터 전달 구현

### 작업 일정(Optional)
2022.10.25 - 2022.10.25 (1일)

### Optional
- HomeView → VideoCollectionView로 전달할 데이터 
  - SectionData
  - [VideoInformation]
  - SectionData의 수정이 불가피하다고 생각됨!
- HomeView → VideoDetailView로 전달할 데이터
  - VideoInformation
