### ISSUE TITLE
[feat] 뷰간 데이터 넘기는 작업

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#75]
### 작업에 대한 간단한 설명
- 뷰간 데이터 넘기기 위한 로직 구현 작업

### TODO
- [x] 피드백 완료 버튼 클릭 시 피드백 Update
- [x] 좋아요 버튼 클릭 시 isFavorite true로 변환
- [x] @commitcomplete 가 넘겨준 데이터에서 영상 데이터 추출 후 재생
- [x] 삭제 버튼 클릭 시 모델 Delete
    - [x] 액션시트로 삭제 재확인 후 뒤로가기구현

### 작업 일정(Optional)
2022.10.26 - 2022.10.26

|작업일자|작업 내용|
|:---:|:---:|
|2022.10.26|피드백 완료 버튼 클릭 시 피드백 Update|
|2022.10.26|좋아요 버튼 클릭 시 isFavorite true로 변환|
|2022.10.26|데이터에서 영상 데이터 추출 후 재생|
|2022.10.26| 삭제 버튼 클릭 시 모델 Delete|

### Optional
- 기본 기능 구현 먼저 하고 상세 디테일 잡는 작업 들어가겠습니다
