### ISSUE TITLE
[feat] 영상 레이어에서 슬라이더 추가

### ISSUE THREAD

**Issue by hminkim** [DeveloperAcademy-POSTECH/MacC-TEAM-8bit#96]
### 작업에 대한 간단한 설명
- 영상을 빠르게 확인해서 분류를 빨리 할 수 있게 하는 Slider 기능을 추가합니다.
- 영상의 재생 시점을 하단 Slider의 게이지를 통해서 보여줍니다.
- 하단 Slider를 옮겨 영상의 재생 시점을 바꿔줍니다.
- 3차 스프린트에 적용할 하이파이 디자인을 일부 반영합니다.

### TODO
- [x] 영상의 재생 시점을 Slider로 보여주는 기능 구현
- [x] Slider를 통해 영상의 재생 시점을 옮겨주는 기능 구현
- [x] 추가 UI: ThumbImage, 성공/실패 버튼, 카드 여러장이 겹쳐져 있는 것처럼 보이는 스켈레톤

### 작업 일정
2022.11.18 - 2022.11.20

|작업일자|작업 내용|
|:---:|:---:|
|2022.11.18|Slider UI 및 로직|
|2022.11.19|Slider 로직 보완|
|2022.11.20|Slider ThumbImage|

### Optional
이어서 할 수 있는 작업 목록
- TimeLabel 추가하기
- 영상 삭제 로직과 버튼 추가하기
